[build]
builder = "python"
root = "travel.app/server-python"
buildCommand = "pip install -r requirements.txt && pip install gunicorn"
startCommand = "cd travel.app/server-python && gunicorn --bind 0.0.0.0:$PORT --timeout 120 app:app"

[deploy]
numReplicas = 1
